### ISSUE TITLE
回覆資訊的內容規格

### ISSUE THREAD

**Issue by erase2004** [martinchiu/twitter-api-2020#27]
![Snipaste_2022-03-01_16-33-54](https://user-images.githubusercontent.com/1367757/156133734-b0af635d-22ce-43ad-a1f3-2d1b06c5f6a8.png)

如圖，回覆資料裡面的`tweetOwnerId`和`tweetOwnerAccount`可以是`null`？

**Comment by martinchiu** [comment]
我看了資料發現，是那篇tweet 已經被刪掉 所以那兩個地方才會顯示null，我修改一下，讓搜尋回覆時不會有刪掉的tweet 的回覆

**Comment by erase2004** [comment]
刪除推文會是硬移除，也就是推文會完全從資料表上移除？
因為我在想，如果是軟移除的話，或許還可以取得當初回覆對象的資訊，
只是推文顯示時，過濾不做顯示，
但如果是硬移除的話，由於參考對象已經消失了，則沒辦法取得當初對象的資訊，
但是回文還是在的，那作法上，前端或許對null的處理，
會是在帳號的地方改顯示為`推文對象已不存在`之類的訊息作為提示

**Comment by martinchiu** [comment]
對！刪除推文是硬移除，資料完全移除
所以在刪除推文的功能上，把推文完全從資料刪除改成，在推文加上一個「delete: true 」的屬性呢？
還是維持硬移除，然後在回覆的部分如果遇到推文被刪掉的account 部分顯示推文對象已不存在
