### ISSUE TITLE
喜愛的推文列表中，顯示用的時間與排序用的時間

### ISSUE THREAD

**Issue by erase2004** [martinchiu/twitter-api-2020#28]
![Snipaste_2022-03-01_16-45-49](https://user-images.githubusercontent.com/1367757/156135606-1d304d91-daba-4dce-92b1-7aa637cd1258.png)
![Snipaste_2022-03-01_16-46-05](https://user-images.githubusercontent.com/1367757/156135614-ef24dcc9-fc6c-4510-bb32-b737ce915e47.png)
![Snipaste_2022-03-01_16-46-14](https://user-images.githubusercontent.com/1367757/156135618-8f1c38c2-43e0-449f-8bf4-9f1233e909da.png)

在`userId: 324`的使用者Profile頁喜愛的列表下，資料裡面的`createdAt`代表關係建立的時間，
仍另一個欄位的時間作為顯示**該則推文的建立時間**，
實作上，希望可以把createdAt留給推文或者回覆的建立時間，
另一個回傳的時間資料欄位作為**排序關係的建立時間**使用

**Comment by martinchiu** [comment]
你的意思是，讓使用者喜歡推文的列表內，排序的依據不是使用者喜歡推文的時間，而是推文建立的時間。那關係建立的時間還需要回傳給前端嗎？

**Comment by erase2004** [comment]
顯示排序的參考 -> 喜愛關係的建立時間
每則推文顯示的時間 -> 推文的建立時間
兩個是不同的時間
每則推文顯示的時間希望維持為`createdAt`
關係建立時間則用另一個`key`值

**Comment by martinchiu** [comment]
我把推文建立時間用 createdAt 屬性代表
關係建立時間用 relationshipCreatedAt 代表

**Comment by erase2004** [comment]
這是更新上正式站了？

**Comment by HUANG-SIH-MAN** [comment]
已經改寫過了，master和heroku已更新
![image](https://user-images.githubusercontent.com/87868469/156167020-c1f2d419-4192-4406-bd8f-9b4cb96f9aa7.png)

**Comment by martinchiu** [comment]
前次更新的版本因為跑線上測試沒過，所以退版，現在已經重新再次部署好了

**Comment by erase2004** [comment]
確認已修改
